### ISSUE TITLE
Validator action should fail nicely for validator versions below 0.10

### ISSUE THREAD

**Issue by ml-evs** [Materials-Consortia/optimade-validator-action#35]
Since v0.10 of optimade-python-tools, the way of calling the validator has changed from `optimade_validator` to `optimade-validator`, so requesting a version <0.10 causes failures. It's not worth us supporting the older version, so we should simply raise an error if the version requested is too low.

**Comment by CasperWA** [comment]
Note that one can also supply git commit SHAs. This means we should find a general way of determining the version of the installed OPTIMADE Python tools. Or said in another way, always having the validator fail prior to installing OPTIMADE Python tools is not possible, making the "fail for version <0.10" a bit slower - but that should be fine?

**Comment by ml-evs** [comment]
I just hacked something together for parsing version numbers, but see the problem with the SHA's... could just handle it both ways, if optimade-validator doesn't exist, then just fall over?

**Comment by CasperWA** [comment]
> I just hacked something together for parsing version numbers, but see the problem with the SHA's... could just handle it both ways, if optimade-validator doesn't exist, then just fall over?

Yeah, please give fixing this a go :) I was just about to do it as well. Two checks are fine as well.
Concerning the SHA, I would either try to check for `optimade-validator`, sure, although this is not explicit - instead I would probably go for retreving the `__version__` and checking it. See this line for an example of retrieving the `__optimade_version__`: https://github.com/Materials-Consortia/optimade-validator-action/blob/13f76aab8ba55d62cdc33312998b68d708ebc058/entrypoint.sh#L99
