### ISSUE TITLE
Default gh_actions_host domain is no longer valid?

### ISSUE THREAD

**Issue by ml-evs** [Materials-Consortia/optimade-validator-action#70]
> I've noticed that the docker image tests have been failing for a few days (see e.g. https://github.com/Materials-Consortia/optimade-python-tools/pull/905/checks?check_run_id=3381031009). It looks like Actions may have removed the `gh_actions_host` access to "localhost"? Any ideas on this @CasperWA?

*Originally posted by @ml-evs in https://github.com/Materials-Consortia/optimade-python-tools/issues/906#issue-975484312*

**Comment by CasperWA** [comment]
[Here's](https://github.com/Materials-Consortia/optimade-validator-action/runs/3381198687?check_suite_focus=true#step:4:47) the issue. The `ip` binary doesn't exist anymore apparently.

**Comment by ml-evs** [comment]
Looks like we should add `set -o pipefail` to the start of some of these `RUN` Docker commands... can't find a nice way to do it globally

**Comment by CasperWA** [comment]
Right. I think the issue is that the `python:3.9` docker image points to a `3.9-bullseye` image now. So I think we should make this much more explicit.

**Comment by CasperWA** [comment]
> Using `python:3.9-alpine` works fine.

Cool. Otherwise I was thinking `slim-buster`?

**Comment by ml-evs** [comment]
Up to you, I guess the packages in `slim-buster` won't change as it has a fixed major version but might in `alpine` (and probably not worth pinning `alpine-3.14` as they release fairly often

**Comment by CasperWA** [comment]
Ah, looks like `alpine` is a much smaller image though (see https://github.com/docker-library/repo-info/tree/master/repos/python).
But we might need more packages still with it, since, e.g., `bash` is not pre-installed.
